"""empty message

Revision ID: 117a4b051a50
Revises: 3d263e56acbc
Create Date: 2014-07-27 22:39:51.217163

"""

# revision identifiers, used by Alembic.
revision = '117a4b051a50'
down_revision = '3d263e56acbc'

from alembic import op
import sqlalchemy as sa


def upgrade():
    ### commands auto generated by Alembic - please adjust! ###
    pass
    ### end Alembic commands ###


def downgrade():
    ### commands auto generated by Alembic - please adjust! ###
    pass
    ### end Alembic commands ###
