"""empty message

Revision ID: 13bde23b4304
Revises: 117a4b051a50
Create Date: 2014-07-27 23:42:18.294778

"""

# revision identifiers, used by Alembic.
revision = '13bde23b4304'
down_revision = '117a4b051a50'

from alembic import op
import sqlalchemy as sa


def upgrade():
    ### commands auto generated by Alembic - please adjust! ###
    pass
    ### end Alembic commands ###


def downgrade():
    ### commands auto generated by Alembic - please adjust! ###
    pass
    ### end Alembic commands ###
