"""empty message

Revision ID: 173f1096c25
Revises: 396bba026115
Create Date: 2014-08-02 22:39:16.042228

"""

# revision identifiers, used by Alembic.
revision = '173f1096c25'
down_revision = '396bba026115'

from alembic import op
import sqlalchemy as sa


def upgrade():
    ### commands auto generated by Alembic - please adjust! ###
    pass
    ### end Alembic commands ###


def downgrade():
    ### commands auto generated by Alembic - please adjust! ###
    pass
    ### end Alembic commands ###
