"""empty message

Revision ID: 23b19d3cd146
Revises: 13bde23b4304
Create Date: 2014-07-27 23:51:59.105469

"""

# revision identifiers, used by Alembic.
revision = '23b19d3cd146'
down_revision = '13bde23b4304'

from alembic import op
import sqlalchemy as sa


def upgrade():
    ### commands auto generated by Alembic - please adjust! ###
    pass
    ### end Alembic commands ###


def downgrade():
    ### commands auto generated by Alembic - please adjust! ###
    pass
    ### end Alembic commands ###
