"""empty message

Revision ID: 24577af857cb
Revises: 562758e6b4ae
Create Date: 2014-07-28 00:31:36.698466

"""

# revision identifiers, used by Alembic.
revision = '24577af857cb'
down_revision = '562758e6b4ae'

from alembic import op
import sqlalchemy as sa


def upgrade():
    ### commands auto generated by Alembic - please adjust! ###
    pass
    ### end Alembic commands ###


def downgrade():
    ### commands auto generated by Alembic - please adjust! ###
    pass
    ### end Alembic commands ###
