"""empty message

Revision ID: 392196b15ad6
Revises: 4b86389d666b
Create Date: 2014-08-04 03:13:52.603022

"""

# revision identifiers, used by Alembic.
revision = '392196b15ad6'
down_revision = '4b86389d666b'

from alembic import op
import sqlalchemy as sa


def upgrade():
    ### commands auto generated by Alembic - please adjust! ###
    pass
    ### end Alembic commands ###


def downgrade():
    ### commands auto generated by Alembic - please adjust! ###
    pass
    ### end Alembic commands ###
