"""empty message

Revision ID: 3bc602ccd5ba
Revises: 550d5a8c8ac6
Create Date: 2014-07-27 21:44:46.109870

"""

# revision identifiers, used by Alembic.
revision = '3bc602ccd5ba'
down_revision = '550d5a8c8ac6'

from alembic import op
import sqlalchemy as sa


def upgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.add_column('user', sa.Column('active', sa.Boolean(), nullable=True))
    op.drop_column('user', 'encrypted_key')
    ### end Alembic commands ###


def downgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.add_column('user', sa.Column('encrypted_key', sa.BLOB(), nullable=True))
    op.drop_column('user', 'active')
    ### end Alembic commands ###
