"""empty message

Revision ID: 3d263e56acbc
Revises: 4b31303a5456
Create Date: 2014-07-27 22:37:48.217379

"""

# revision identifiers, used by Alembic.
revision = '3d263e56acbc'
down_revision = '4b31303a5456'

from alembic import op
import sqlalchemy as sa


def upgrade():
    ### commands auto generated by Alembic - please adjust! ###
    pass
    ### end Alembic commands ###


def downgrade():
    ### commands auto generated by Alembic - please adjust! ###
    pass
    ### end Alembic commands ###
