"""empty message

Revision ID: 3fc3bb13455b
Revises: 42dae0b3f7c
Create Date: 2014-07-27 22:07:39.728197

"""

# revision identifiers, used by Alembic.
revision = '3fc3bb13455b'
down_revision = '42dae0b3f7c'

from alembic import op
import sqlalchemy as sa


def upgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.add_column('user', sa.Column('status', sa.Integer(), nullable=True))
    ### end Alembic commands ###


def downgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('user', 'status')
    ### end Alembic commands ###
