"""empty message

Revision ID: 42dae0b3f7c
Revises: 456907a97ba
Create Date: 2014-07-27 21:56:43.381638

"""

# revision identifiers, used by Alembic.
revision = '42dae0b3f7c'
down_revision = '456907a97ba'

from alembic import op
import sqlalchemy as sa


def upgrade():
    ### commands auto generated by Alembic - please adjust! ###
    pass
    ### end Alembic commands ###


def downgrade():
    ### commands auto generated by Alembic - please adjust! ###
    pass
    ### end Alembic commands ###
