"""empty message

Revision ID: 441a2b4764db
Revises: 4f0c53cfea
Create Date: 2014-07-28 00:22:15.942545

"""

# revision identifiers, used by Alembic.
revision = '441a2b4764db'
down_revision = '4f0c53cfea'

from alembic import op
import sqlalchemy as sa


def upgrade():
    ### commands auto generated by Alembic - please adjust! ###
    pass
    ### end Alembic commands ###


def downgrade():
    ### commands auto generated by Alembic - please adjust! ###
    pass
    ### end Alembic commands ###
