"""empty message

Revision ID: 4b31303a5456
Revises: 3fc3bb13455b
Create Date: 2014-07-27 22:29:28.369696

"""

# revision identifiers, used by Alembic.
revision = '4b31303a5456'
down_revision = '3fc3bb13455b'

from alembic import op
import sqlalchemy as sa


def upgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.add_column('user', sa.Column('username', sa.String(length=16), nullable=True))
    op.create_index(op.f('ix_user_username'), 'user', ['username'], unique=True)
    ### end Alembic commands ###


def downgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_user_username'), table_name='user')
    op.drop_column('user', 'username')
    ### end Alembic commands ###
