"""empty message

Revision ID: 4f0c53cfea
Revises: 23b19d3cd146
Create Date: 2014-07-28 00:02:41.191403

"""

# revision identifiers, used by Alembic.
revision = '4f0c53cfea'
down_revision = '23b19d3cd146'

from alembic import op
import sqlalchemy as sa


def upgrade():
    ### commands auto generated by Alembic - please adjust! ###
    pass
    ### end Alembic commands ###


def downgrade():
    ### commands auto generated by Alembic - please adjust! ###
    pass
    ### end Alembic commands ###
