"""empty message

Revision ID: 550d5a8c8ac6
Revises: 3d6d3b9a859a
Create Date: 2014-07-27 17:35:19.989608

"""

# revision identifiers, used by Alembic.
revision = '550d5a8c8ac6'
down_revision = '3d6d3b9a859a'

from alembic import op
import sqlalchemy as sa


def upgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.add_column('user', sa.Column('password', sa.String(length=60), nullable=True))
    ### end Alembic commands ###


def downgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('user', 'password')
    ### end Alembic commands ###
