"""empty message

Revision ID: 597162ae02ff
Revises: 173f1096c25
Create Date: 2014-08-02 22:40:26.179765

"""

# revision identifiers, used by Alembic.
revision = '597162ae02ff'
down_revision = '173f1096c25'

from alembic import op
import sqlalchemy as sa


def upgrade():
    ### commands auto generated by Alembic - please adjust! ###
    pass
    ### end Alembic commands ###


def downgrade():
    ### commands auto generated by Alembic - please adjust! ###
    pass
    ### end Alembic commands ###
