"""empty message

Revision ID: 8d91329257e
Revises: 46558bf2142a
Create Date: 2014-07-28 19:34:34.877233

"""

# revision identifiers, used by Alembic.
revision = '8d91329257e'
down_revision = '46558bf2142a'

from alembic import op
import sqlalchemy as sa


def upgrade():
    ### commands auto generated by Alembic - please adjust! ###
    pass
    ### end Alembic commands ###


def downgrade():
    ### commands auto generated by Alembic - please adjust! ###
    pass
    ### end Alembic commands ###
